services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: martins
      POSTGRES_PASSWORD: bdrn.admin
      POSTGRES_DB: rnv_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_data:
